s10582/src/main/java/com/example/s10582/domain/Anime.java
package com.example.s10582.domain;



public class Anime {
	
	private String title = "Title";
	private String genre = "Genre";
	private int year;
	private String episodes = "Episodes";
	private String studio = "Studio";
	
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public String getGenre() {
		return genre;
	}
	public void setGenre(String genre) {
		this.genre = genre;
	}
	public int getYear(){
		return year;
	}
	public void setYear(int year) {
        this.year = year;
	}
	public String getEpisodes() {
		return episodes;
	}
	public void setEpisodes(String episodes) {
		this.episodes = episodes;
	}
	
	public String getStudio() {
		return studio;
	}
	public void setStudio(String studio) {
		this.studio = studio;
	}
}

s10582/src/main/java/com/example/s10582/web/AnimeFormBean.java
package com.example.s10582.web;

import java.io.Serializable;


import javax.enterprise.context.SessionScoped;
import javax.faces.model.ListDataModel;
import javax.inject.Inject;
import javax.inject.Named;

import com.example.s10582.domain.Anime;
import com.example.s10582.service.AnimeManager;

@SessionScoped
@Named("animeBean")
public class AnimeFormBean implements Serializable {

	private static final long serialVersionUID = 1L;

	private Anime anime = new Anime();

	private ListDataModel<Anime> animes = new ListDataModel<Anime>();

	@Inject
	private AnimeManager an;

	public Anime getAnime() {
		return anime;
	}

	public void setAnime(Anime anime) {
		this.anime = anime;
	}

	public ListDataModel<Anime> getAllAnimes() {
		animes.setWrappedData(an.getAllAnimes());
		return animes;
	}

	
	public String addAnime() {
		an.addAnime(anime);
		return "showAnimes";
		
	}

	public String deleteAnime() {
		Anime animeToDelete = animes.getRowData();
		an.deleteAnime(animeToDelete);
		return null;
	}

}

s10582/src/main/webapp/addAnime.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/templates/default.xhtml">
	<ui:define name="content">
		<h:form id="animeform">
			<h:panelGrid columns="4">

				<h:outputText value="#{msg.animetitleLabel}" />
				<h:inputText id="title" value="#{animeBean.anime.title}" />
				<h:outputText value="#{msg.animegenreLabel}" />
				<h:inputText id="genre" value="#{animeBean.anime.genre}" />
				<h:outputText value="#{msg.animeyearLabel}" />
				<h:inputText id="year" value="#{animeBean.anime.year}" />
				<h:outputText value="#{msg.animeepisodesLabel}" />
				<h:inputText id="episodes" value="#{animeBean.anime.episodes}" />
				<h:outputText value="#{msg.animestudioLabel}" />
				<h:inputText id="studio" value="#{animeBean.anime.studio}" />

			
			</h:panelGrid>

			<h:commandButton value="#{msg.animeFormOKButton}"
				action="#{animeBean.addAnime}" />
				
			<h:panelGrid>
				<h:messages showDetail="#{true}" showSummary="#{false}" />
			</h:panelGrid>
		</h:form>
	</ui:define>
</ui:composition>

s10582/src/main/webapp/index.jsp
<% response.sendRedirect("showAnimes.jsf"); %>

s10582/src/main/webapp/showAnimes.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/templates/default.xhtml">
	
	<ui:define name="content">
	
    <h:form>
    
     <h:dataTable value="#{animeBean.allAnimes}" var="item">
      <f:facet name="header">#{msg.animeAllLabel}</f:facet>
      
      <h:column>
        <f:facet name="header">#{msg.animetitleLabel}</f:facet>
        #{item.title}
      </h:column>
       <h:column>
        <f:facet name="header">#{msg.animegenreLabel}</f:facet>
        #{item.genre}
      </h:column>
      <h:column>
        <f:facet name="header">#{msg.animeyearLabel}</f:facet>
        #{item.year}
      </h:column>
       <h:column>
        <f:facet name="header">#{msg.animeepisodesLabel}</f:facet>
        #{item.episodes}
      </h:column>
       <h:column>
        <f:facet name="header">#{msg.animestudioLabel}</f:facet>
        #{item.studio}
      </h:column>
      

      <h:column>
        <f:facet name="header">#{msg.action}</f:facet>
        <h:commandLink value="#{msg.actionDelete}" action="#{animeBean.deleteAnime}"/>
      </h:column>
     </h:dataTable>
          <h:commandLink action="addAnime?faces-redirect=true">
			<h:outputText value="#{msg.animeAddLabel}" />
	  </h:commandLink>
    </h:form>
      
	</ui:define>
	
</ui:composition>

s10582/src/main/webapp/templates/default.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<h:head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title><ui:insert name="windowTitle">#{msg.mainWindowTitle}</ui:insert>
	</title>
</h:head>
<h:body>
  <h:outputStylesheet library="css" name="default.css" target="body" />
	<div class="heading">
	  <ui:insert name="heading">
       #{msg.mainHeading}
     </ui:insert>
    </div>
	<div class="menuAndContent">
	
	  <div class="content">
	     <ui:insert name="content" />
       </div>
	</div>
</h:body>
</html>